name: Schedule workflow

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Dispatch
        run: ./dispatch.sh
        env:
          YOUR_TOKEN: ${{ secrets.YOUR_TOKEN }}
          
